### ISSUE TITLE
Docker version seems not to work on arm64 (Raspberry Pi)

### ISSUE THREAD

**Issue by nordcomputer** [antonengelhardt/Kicktipp-Bot#3]
I tried to set up the docker container via docker-compose.yml but it seems not to work on a Raspberry Pi. 
It is working fine on my main machine (Debian).

My docker-compose.yml:

```
version: '3'

services:
  bot:
    image: antonengelhardt/kicktipp-bot:latest
    container_name: kicktipp-bot
    restart: always
    environment:
      - KICKTIPP_EMAIL=${KICKTIPP_EMAIL}
      - KICKTIPP_PASSWORD=${KICKTIPP_PASSWORD}
      - KICKTIPP_NAME_OF_COMPETITION=${KICKTIPP_NAME_OF_COMPETITION}
```

The docker logs:

```
docker-compose up
Creating network "kicktippbot_default" with the default driver
Pulling bot (antonengelhardt/kicktipp-bot:latest)...
latest: Pulling from antonengelhardt/kicktipp-bot
bbeef03cda1f: Pull complete
f049f75f014e: Pull complete
56261d0e6b05: Pull complete
9bd150679dbd: Pull complete
5b282ee9da04: Pull complete
03f027d5e312: Pull complete
41b6012c8972: Pull complete
e84941e8ff4e: Pull complete
8848ba81439a: Pull complete
5f78639e6ef0: Pull complete
da1870f2e0a0: Pull complete
43afa570d098: Pull complete
879b4ec8dcd2: Pull complete
4f4fb700ef54: Pull complete
de128f633af7: Pull complete
527535a1882f: Pull complete
2d6e99a4b627: Pull complete
901cbeda9d62: Pull complete
81b24fb0f729: Pull complete
Digest: sha256:5b515cd51940284917ae3213a5923aad47cd98213f4b2b7feb2a03419371807f
Status: Downloaded newer image for antonengelhardt/kicktipp-bot:latest
Creating kicktipp-bot ... done
Attaching to kicktipp-bot
kicktipp-bot | exec /usr/local/bin/python: exec format error
kicktipp-bot exited with code 1
kicktipp-bot | exec /usr/local/bin/python: exec format error
kicktipp-bot | exec /usr/local/bin/python: exec format error
kicktipp-bot | exec /usr/local/bin/python: exec format error
kicktipp-bot exited with code 1
kicktipp-bot | exec /usr/local/bin/python: exec format error
kicktipp-bot | exec /usr/local/bin/python: exec format error
kicktipp-bot | exec /usr/local/bin/python: exec format error
kicktipp-bot | exec /usr/local/bin/python: exec format error
kicktipp-bot exited with code 1
kicktipp-bot | exec /usr/local/bin/python: exec format error
kicktipp-bot | exec /usr/local/bin/python: exec format error
kicktipp-bot | exec /usr/local/bin/python: exec format error
kicktipp-bot | exec /usr/local/bin/python: exec format error
kicktipp-bot | exec /usr/local/bin/python: exec format error
kicktipp-bot exited with code 1
kicktipp-bot | exec /usr/local/bin/python: exec format error
kicktipp-bot | exec /usr/local/bin/python: exec format error
kicktipp-bot | exec /usr/local/bin/python: exec format error
kicktipp-bot | exec /usr/local/bin/python: exec format error
kicktipp-bot | exec /usr/local/bin/python: exec format error
kicktipp-bot | exec /usr/local/bin/python: exec format error
kicktipp-bot exited with code 1

```
